### ISSUE TITLE
Errors are muted by default

### ISSUE THREAD

**Issue by ivan-kleshnin** [mmkal/slonik-tools#44] opened 2019-10-11 17:09 UTC
From the docs:

> log | how information about the migrations will be logged. 
> You can set to () => {} to prevent logs appearing at all. | 
> Default: console.log

I was thinking this package is broken as no errors appeared when they should.
Then I tried to set `log: console.log` as a last resort.
To my surprise it helped. So the default value of `log` is probably not `console.log` or it's not used correctly.

https://github.com/mmkal/slonik-tools/blob/master/packages/migrator/src/index.ts#L34

Probably this:

```diff
export const setupSlonikMigrator = ({
  slonik,
  migrationsPath,
  migrationTableName = 'migration',
-  log: _log = console.log,
+  log = _log = console.log,
  mainModule,
}: SlonikMigratorOptions) => {
```

**Comment by mmkal** [comment] 2019-10-27 23:08
Hi, thanks for reporting. Which errors were you expecting to see?

**Comment by mmkal** [comment] 2020-02-29 04:05
@ivan-kleshnin I'm not able to reproduce this; closing. Happy to reopen if you can let me know your repro.

**Closed by mmkal** 2020-02-29 04:05 UTC

**Comment by derekchiang** [comment] 2020-03-31 21:43
I'm running into the same issue.  I have an error in my migration script but no error was printed and no tables were created.  The library just logged:

```
migrations in database: []
== 2020-03-29T18-33.create-tables: migrating =======
```

And that's it.  In my case, even setting `log: console.log,` doesn't help.

**Comment by derekchiang** [comment] 2020-03-31 21:56
False alarm!   I was looking at the wrong place.
