### ISSUE TITLE
pg-native breaks nullability tracking

### ISSUE THREAD

**Issue by panmau** [mmkal/slonik-tools#334] opened 2021-07-13 18:18 UTC
When using slonik-typegen for generating types for queries on columns that are defined as `NOT NULL`, it still generates the type with a possible null.
For example:
```
/** regtype: `uuid` */
player_two_id: string | null;
```

These should be generated just as string. I'm not sure how hard it is to read this info from the db.

**Comment by mmkal** [comment] 2021-07-13 21:09
It's pretty hard tbh! To be confident that a field is non-null, the query needs to be statically analyseable since postgres doesn't really bother keeping track of it. Which means

```sql
with foo as (select * from bar)
select id from foo
```

Unfortunately won't be marked as non-null even if the `id` column from `bar` is. If you could share the query that player_two_id is coming from, it may be possible to make the query parser smarter. Failing that, you could use a `writeTypes` hook, if you're happy getting a bit into the weeds.

**Comment by panmau** [comment] 2021-07-14 08:19
That's what I suspected. For me this is just a nice to have feature, when some of the more annoying things are solved.

My query is like this:
```
select player_two_id from my_table where id = ${id}
```

**Comment by mmkal** [comment] 2021-07-14 12:57
@panmau for a simple query like that, it should be able to figure out that the column is non-null. If you have a small reproducible example which includes the `create table my_table(...)` statement, I can look into why it isn't detecting the nullability.

**Comment by panmau** [comment] 2021-07-14 18:49
It's always very helpful to create a minimal repro!

I found out that this only happens when the pg-native package is somewhere in the dependency tree. See the repro here: https://github.com/panmau/slonik-tools-repros/tree/not-null

Any idea on why this seems to be the case?

---

Context on why I have it in my dependency tree:
In my project I have specified pg-native in my packageExtensions of my yarnrc because yarn 2 together with Plug N' Play is a lot stricter with the package requires. 
So I added it to solve this error that I wasn't able to yet address upstream:
```
Module not found: Error: pg tried to access pg-native (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
```

**Comment by mmkal** [comment] 2021-07-15 05:07
@panmau I don't know why, no. I've never used slonik with pg-native. But since the usage of slonik is really just an implementation detail in this package, in the linked PR I'm just disabling usage of pg-native explicitly. I don't want to support two different drivers (although of course I do want the tool to work fine if _you_ use pg-native).

Maybe someone will convince me one day that pg-native gives some big enough benefit that it'd be worth the maintenance overhead to use. In the meantime, please feel free to leave any comments on the PR, otherwise I'll merge it in a day or two. If you're in a hurry to get rid of those nulls, you can also workaround this yourself, by passing `preferNativeBindings: false` to your slonik `createPool` options.

**Comment by panmau** [comment] 2021-07-15 07:15
Nice thank you. That fix works fine for me. And I'm not in a hurry for that as I don't have a lot of types yet.

**Closed** 2021-07-15 12:32 UTC
Labels: @slonik/typegen
